blank_issues_enabled: false
contact_links:
  - name: Netdata Agent
    url: https://github.com/netdata/netdata/issues/new/choose
    about: Get help with the FOSS agent, submit a bug or feature request 
  - name: Question
    url: https://community.netdata.cloud
    about: We offer community-driven support on our Community forums
